# Generated by Django 5.0.1 on 2024-02-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                ("todo_id", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=256)),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True)),
                ("date_end", models.DateTimeField(blank=True, null=True)),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="False=Incomplete, True=Completed"
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
